# Site settings
name: aqua-everfit Homepage
description: The Homepage of the aqua-everfit company.

title: aqua everfit Bewegungsbad in Höxter
url: "http://www.aqua-everfit.de/" # The base hostname & protocol for your site. Use it if you need absolute URL's

author: lk
author_email: l.knoke@colorplus.de

# Use this for production
#sass:
#    style: :compressed

include: ["_pages"]
exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
